M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Tue Sep  6 16:13:56 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-06T16:13:56-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
%
G90
G05
T1
X7.0613Y-3.1461
X7.0613Y-3.3737
T2
X4.375Y-2.49
X4.45Y-5.24
X7.21Y-2.415
T0
M30
